### ISSUE TITLE
error about Swin & Vit

### ISSUE THREAD

**Issue by Lsz-20** [jacobgil/pytorch-grad-cam#160]
there is something wrong when i run usage_example:viT & swin
Vit:
it shows a problem：
File "vit_example.py", line 6, in <module>
    from pytorch_grad_cam import GradCAM, \
ImportError: cannot import name 'FullGrad' from 'pytorch_grad_cam' (/opt/conda/envs/py38_torch1.7.1/lib/python3.8/site-packages/pytorch_grad_cam/__init__.py)

Swin:
it shows this:
Exception ignored in: <function BaseCAM.__del__ at 0x7f5450fbc290>
Traceback (most recent call last):
  File "/home/lsz/pytorch-grad-cam-master/pytorch_grad_cam/base_cam.py", line 191, in __del__
    self.activations_and_grads.release()
AttributeError: 'ScoreCAM' object has no attribute 'activations_and_grads'
Traceback (most recent call last):
  File "/home/lsz/pytorch-grad-cam-master/usage_examples/swinT_example.py", line 100, in <module>
    reshape_transform=reshape_transform)
TypeError: __init__() got an unexpected keyword argument 'target_layer'

Thanks~

**Comment by jacobgil** [comment]
Thanks, yes it should be target_layers. I pushed a fix to that 

For the vit_example Fullgrad error - wasn't able to reproduce that.
Are you using the latest version?

**Comment by Lsz-20** [comment]
> I tried with "target_layers" and the code runs successfully.

your swin can run successfully？Please tell me your versions you are using

**Comment by Lsz-20** [comment]
> Thanks, yes it should be target_layers. I pushed a fix to that
> 
> For the vit_example Fullgrad error - wasn't able to reproduce that. Are you using the latest version?
I am using the latest version,and found that py37+torch1.8 can run vit well ,but py3.7+torch1.7 show me the error.
and for swin, it still show me the error about ' target_layers', i have seen the 'target_layer = model.layers[-1].blocks[-1].norm2' in the code yet.
it same as #158 
thanks

**Comment by jacobgil** [comment]
Can you please retry with the latest code from this rep?
`target_layer` should be fully replaced in favor of `target_layers`
