### ISSUE TITLE
__init__() got an unexpected keyword argument 'ablation_layer'

### ISSUE THREAD

**Issue by Atharva-cloud** [jacobgil/pytorch-grad-cam#208]
Facing this error while doing it for custom as well as pre-trained model. 
![1646646086558370200731822119784](https://user-images.githubusercontent.com/76895421/157006428-3f5bda16-c83d-48c2-9eb3-8834d94c9f64.jpg)

**Comment by jacobgil** [comment]
Hi,
This issue should be fixed now.
Please git pull and try again.

**Comment by Atharva-cloud** [comment]
Hi, Thanks for your quick response. I tried pulling the repo again(multiple times actually), but the error remains the same. There seems to be some other issue here.
Link to notebook: https://colab.research.google.com/drive/1ME7oKOHUfU8oYO022kffrnyAqOOL8oNr#scrollTo=S2AOw4U7nfgU
Thank you.

**Comment by jacobgil** [comment]
Hello, I looked in the notebook code,
the problem seems to be that it passes ablation_layer, however only AblationCAM accepts that.
Please follow this:
```
    if args.method == "ablationcam":
        cam = methods[args.method](model=model,
                                   target_layers=target_layers,
                                   use_cuda=args.use_cuda,
                                   reshape_transform=reshape_transform,
                                   ablation_layer=AblationLayerVit())
    else:
        cam = methods[args.method](model=model,
                                   target_layers=target_layers,
                                   use_cuda=args.use_cuda,
                                   reshape_transform=reshape_transform)
```

AblationCAM can give  good results for Vision Transformers, so it's worth trying that as well.

**Comment by Atharva-cloud** [comment]
Thank you so much for your time and assistance. That worked.

**Comment by Atharva-cloud** [comment]
Hello Jacob.
I have come across an error while implementing gradcam on DenseNet121.
PFA the screenshot of the code and the error.
Any help would be appreciated.
Thank you and Regards,
Atharva Yeola
[image: image.png]
[image: image.png]

**Comment by Atharva-cloud** [comment]
[image: image.png]
